# Generated by Django 5.2.6 on 2025-10-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='bio',
        ),
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='candidates/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='matric_no',
            field=models.CharField(default=210561000, max_length=9, unique=True),
        ),
    ]
