# Generated by Django 5.2.6 on 2025-10-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_remove_candidate_bio_candidate_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='matric_no',
            field=models.CharField(blank=True, default=None, max_length=9, null=True, unique=True),
        ),
    ]
