# Generated by Django 5.2.6 on 2025-10-09 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0003_alter_user_matric_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='election',
        ),
    ]
