# Generated by Django 5.2.6 on 2025-10-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0004_remove_candidate_election'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
