# Generated by Django 5.2.6 on 2025-10-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0007_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='have_voted',
            field=models.BooleanField(default=False),
        ),
    ]
